# Generated by Django 3.0.3 on 2020-03-28 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Filmatory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movienames',
            old_name='searchtext',
            new_name='search',
        ),
        migrations.RemoveField(
            model_name='movienames',
            name='datefield',
        ),
    ]
