# Generated by Django 3.0.3 on 2020-03-28 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Filmatory', '0002_auto_20200328_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='movienames',
            name='datefi',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
